# Site settings
title: Edward Andrew Robinson
description: 'Head of architecture at Hubba'
url: 'http://earobinson.net'
baseurl: ''
google_analytics: UA-116652735-1
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Edward Andrew Robinson'
  email: contact@earobinson.net
  twitter_username: earobinson
  facebook_username: edwardarobinson
  github_username:  earobinson
  linkedin_username:  earobinson42

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
